### ISSUE TITLE
Transpiling between JavaScript to QML

### ISSUE THREAD

**Issue by giorgiozoppi** [status-im/react-native-desktop-qt#568]
# For Discussion

It would be nice, and i would help to reimplement all your compoennt to :
https://www.youtube.com/watch?v=p8re60C3Huw

**Comment by vkjr** [comment]
@giorgiozoppi, hi!
You provided a link to some experimental technology ReaQt Native and it looks like it is not supported in any way. I can't even google anything about it except that video.
Could you please explain in more details what do you suggest?

**Comment by giorgiozoppi** [comment]
QML is barely supported native by qt, instead using node rendering the stuff, simply map each react component to a QML component but i don't know how much costs.
