### ISSUE TITLE
Redesign Roadmap

### ISSUE THREAD

**Issue by baarkerlounger** [status-im/react-native-desktop-qt#591]
Is there a public roadmap for the redesign?

Also more generally what is the status of the project? Should it be considered not ready for building on/porting apps with until the redesign is complete or is it expected to be usable already?

Is there any documentation for porting existing react-native apps?

**Comment by vkjr** [comment]
Hi @baarkerlounger!
There is no public roadmap for redesign but most of it is done already:
- desktop version code separated from `react-native` code
- internal js engine from Qt can be used
- compatibility with `react-native` moved to version 0.60

You can use it right now but recent changes were tested only on mac.
I'll update docs soon. 
This doc should work for you - https://github.com/status-im/react-native-desktop-qt/blob/master/docs/CreateNewApp.md
