### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by niwla23** [status-im/react-native-desktop-qt#597]
Last commit was on may 2020 or so

**Comment by vkjr** [comment]
Yes, project is not supported anymore since there is no demand for it.

**Comment by igorcafe** [comment]
Oh, my heart is broken
I wanted so bad something like that skyrocketing

**Comment by giorgiozoppi** [comment]
is there any commercial interest by qt customers on this? I am on leave, no promises, but if there's a group interested on this.

**Comment by vkjr** [comment]
Haven't seen any interest, unfortunately. Some time ago when the project was about to close inside Status company I was thinking about continuing it on my own. I sent out a bunch of emails to people who starred this repo asking if they need it or how it can be used within their companies. Unfortunately, the rate of replies told me there is no demand right now.
